source 'https://cdn.cocoapods.org/'
source 'https://github.com/idwise/ios-sdk'
deployment_target = '13.0'
platform :ios, deployment_target
project 'IDWiseDemo.xcodeproj'
inhibit_all_warnings!
use_frameworks!

target 'IDWiseDemo' do
  pod 'ExampleModule', :path => '../example-module/'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
end
